import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner/Banner";
import Image from "next/image";
import Card from "../components/Card/Card";
import coffeeStoresData from "../data/coffee-stores.json";

export const getStaticProps = async () => {
  console.log("this is from getStaticProps");
  return { props: { coffeeStores: coffeeStoresData } };
};

export default function Home(props) {
  console.log("This is from Home");
  const handleBannerButtonClick = () => {
    console.log("Banner button clicked");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="view nearby coffee shops"
          handleClick={handleBannerButtonClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero image"
          />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Feni Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => (
                <Card
                  key={coffeeStore.id}
                  href={`/coffee-store/${coffeeStore.id}`}
                  imgUrl={coffeeStore.imgUrl}
                  name={coffeeStore.name}
                  className={styles.card}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
