import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner/Banner";
import Image from "next/image";
import Card from "../components/Card/Card";

export default function Home() {
  const handleBannerButtonClick = () => {
    console.log("Banner button clicked");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="view nearby coffee shops"
          handleClick={handleBannerButtonClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero image"
          />
        </div>
        <div className={styles.cardLayout}>
          <Card
            href="/coffee-store/Raju Coffee Store"
            imgUrl="/static/hero-image.png"
            name="Raju Coffee Store"
            className={styles.card}
          />
          <Card
            href="/coffee-store/Raju Coffee Store"
            imgUrl="/static/hero-image.png"
            name="Raju Coffee Store"
            className={styles.card}
          />
          <Card
            href="/coffee-store/Raju Coffee Store"
            imgUrl="/static/hero-image.png"
            name="Raju Coffee Store"
            className={styles.card}
          />
        </div>
      </main>
    </div>
  );
}
